{
  "jobId": "d509140f-cd3c-48d4-bf66-11928be0ebe2",
  "status": "error",
  "stage": "error",
  "progress": 10,
  "createdAt": "2025-10-16T09:39:05.518Z",
  "updatedAt": "2025-10-16T09:46:33.158Z",
  "email": "bh@email.com",
  "youtubeUrl": "https://www.youtube.com/watch?v=dtJ8N407brM",
  "clips": [],
  "error": "Download failed: All formats failed. Last error: yt-dlp exited with code 1: Traceback (most recent call last):\n  File \u001b[35m\"__main__.py\"\u001b[0m, line \u001b[35m17\u001b[0m, in \u001b[35m<module>\u001b[0m\n  File \u001b[35m\"yt_dlp/__init__.py\"\u001b[0m, line \u001b[35m1071\u001b[0m, in \u001b[35mmain\u001b[0m\n  File \u001b[35m\"yt_dlp/__init__.py\"\u001b[0m, line \u001b[35m968\u001b[0m, in \u001b[35m_real_main\u001b[0m\n  File \u001b[35m\"yt_dlp/YoutubeDL.py\"\u001b[0m, line \u001b[35m1000\u001b[0m, in \u001b[35m__exit__\u001b[0m\n  File \u001b[35m\"yt_dlp/YoutubeDL.py\"\u001b[0m, line \u001b[35m1003\u001b[0m, in \u001b[35mclose\u001b[0m\n  File \u001b[35m\"yt_dlp/YoutubeDL.py\"\u001b[0m, line \u001b[35m995\u001b[0m, in \u001b[35msave_cookies\u001b[0m\n  File \u001b[35m\"yt_dlp/cookies.py\"\u001b[0m, line \u001b[35m1321\u001b[0m, in \u001b[35msave\u001b[0m\n  File \u001b[35m\"contextlib.py\"\u001b[0m, line \u001b[35m141\u001b[0m, in \u001b[35m__enter__\u001b[0m\n  File \u001b[35m\"yt_dlp/cookies.py\"\u001b[0m, line \u001b[35m1276\u001b[0m, in \u001b[35mopen\u001b[0m\n\u001b[1;35mFileNotFoundError\u001b[0m: \u001b[35m[Errno 2] No such file or directory: '/app/cookies.txt'\u001b[0m\n[PYI-11952:ERROR] Failed to execute script '__main__' due to unhandled exception!\n",
  "expiresAt": 1760615493158,
  "message": "Downloading video..."
}